### ISSUE TITLE
Which version of node?

### ISSUE THREAD

**Issue by mattcvincent** [esack7/moby-dick-project#6]
Hi Isaac.  Can you share which version of node you used for this project?  I've tried using a couple versions of node to build:

- node v10.0.0 (npm v5.6.0)
- node v9.11.1 (npm v5.6.0)

and I get the following error on both.

```bash
$ npm run prebuild

> moby-dick-project@1.0.0 prebuild /Users/mattvincent/Documents/code/moby-dick-project
> node ./pre_build/index.js

/Users/mattvincent/Documents/code/moby-dick-project/pre_build/handleBook.js:64
      if (err) throw err;
               ^
```

**Comment by esack7** [comment]
Sorry for the delayed response @mattcvincent.  I used node v9.4.0 for this project.

**Comment by esack7** [comment]
I am going to update node and address this error.

**Comment by esack7** [comment]
I have been working on a laptop running Ubuntu 18.04.  I wasn't able to reproduce the error on my machine, so I will try and this on a Windows machine and see if I get that error.

**Comment by esack7** [comment]
@mattcvincent, I fixed the error with the following PR: https://github.com/esack7/moby-dick-project/pull/7

**Comment by mattcvincent** [comment]
Thanks @esack7 !  Everything works for me (in both node `v9.11.1` & `v10.0.0`) now!
